// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo8kz05_TcWu0xze9-YprFrqJIl7GZub0',
    appId: '1:391189450353:web:28837f6020dae94d0a55d0',
    messagingSenderId: '391189450353',
    projectId: 'crud-80c39',
    authDomain: 'crud-80c39.firebaseapp.com',
    storageBucket: 'crud-80c39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApcJS8A2UaWlOG23-Wtl_g3Zvdlx6hV9c',
    appId: '1:391189450353:android:e0121915026ae5960a55d0',
    messagingSenderId: '391189450353',
    projectId: 'crud-80c39',
    storageBucket: 'crud-80c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60TNOHQht4Y9bBsfVZ_rVkc5lsiExk4U',
    appId: '1:391189450353:ios:55d15bdd19f2d7f70a55d0',
    messagingSenderId: '391189450353',
    projectId: 'crud-80c39',
    storageBucket: 'crud-80c39.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60TNOHQht4Y9bBsfVZ_rVkc5lsiExk4U',
    appId: '1:391189450353:ios:06f491a0b826a9af0a55d0',
    messagingSenderId: '391189450353',
    projectId: 'crud-80c39',
    storageBucket: 'crud-80c39.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
